# Generated by Django 2.2.6 on 2020-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
