# Generated by Django 2.2.6 on 2020-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0002_computer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
    ]
