# Generated by Django 2.2.6 on 2020-11-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0003_auto_20201105_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='Operating_system',
            field=models.CharField(blank=True, choices=[('windows 10', 'windows 10'), ('windows 8', 'windows 8'), ('Linux', 'Linux')], max_length=30, null=True),
        ),
    ]
