# Generated by Django 2.2.6 on 2020-11-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0004_computer_operating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatingsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operating_system', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='Operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computersystem.Operatingsystem'),
        ),
    ]
