# Generated by Django 2.2.6 on 2020-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0005_auto_20201105_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer',
            field=models.ImageField(default='default.jpg', upload_to='computers'),
        ),
    ]
