# Generated by Django 2.2.6 on 2020-12-16 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computersystem', '0006_computer_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='computers/'),
        ),
    ]
